# -*- coding: utf-8 -*-
"""Salinan dari Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adWbLDtrIrR2Ow1Nzdr84VGRd9J0IfIi

kode python DA RevoU
"""

import pandas as pd

"""membca data csv"""

salary = pd.read_csv ("salary_dataset_2.csv")

salary

"""check tipe data bfr"""

salary.info()

"""check data duplicate """

salary = salary.drop_duplicates()

salary.info()

"""check data kosong"""

salary.isna().sum()

"""namatable[(dibareng dgn naman tebl )kolom.fungsi]"""

salary = salary[~salary['salary'].isna()]

"""ketika mau drop data ,pastikan jumlah datanya tidak anyak tau segnifikan. conntoh data ini,ada satu baris kosong dari 565 baris, maka data kosong hanya 0,17 % sehingga dta bisa di drop/delet"""

salary.info()

"""cek data error"""

salary['work_year'].unique()

salary['salary'].unique()

"""change type data"""

salary.info()

"""merubah type data salary

membenahi data error
"""

salary['salary']=salary['salary'].replace('20000;0;','20000')

salary.info()

salary['salary']=salary['salary'].astype(int)

salary['salary']=salary['salary'].replace('20000;0','20000')

salary['salary']=salary['salary'].astype(int)

"""check outlyer

kita hrus mndeteksi apakh ada data outlier aytua tidak
"""

#Before
salary.boxplot(column='salary_in_usd')

"""stndr defiasi tinggi berrti ada outlier"""

salary['salary_in_usd'].describe()

"""batas atas = Q3+1.5X (Q3.Q1). batas bawah =Q1-1.5X(Q3-Q1)"""

q1= salary['salary_in_usd'].quantile(0.25)
q3= salary['salary_in_usd'].quantile(0.75)
upper_limit= q3 + (1.5*(q3-q1))
lower_limit= q1 - (1.5*(q3-q1))

salary = salary[salary['salary_in_usd'] > lower_limit]
salary =salary[salary['salary_in_usd'] < upper_limit]
salary['salary_in_usd'].describe()

"""pertama di simpan dulu dalam type file

"""

#after
salary.boxplot(column='salary_in_usd')

salary.info()

salary.to_csv('salary_cleanned.csv')

from google.colab import files
files.download('salary_cleanned.csv')